import { IMockData } from "./types";

export const mockData: IMockData[] = [
  {
    token: "usdt",
    tokenAddress: "ffsdfsdfsdfdsf",
    rebalancerAddress: "fdsfdsfsdfsf",
    tokenPriceInUsd: 1,
    tokenPrice24HrChangeInPercentages: 1,
    tokenPrice24HrChangeInUsd: 1,
    apr: 1.5,
    funds: 1230000022,
    avgApr: 1.2,
    earned: 1232323,
    decimals: 1,
    deposit: 0,
    borrowRate: 12.5,
    borrowed: 1234334,
    risk: 1
  },
  {
    token: "usdc",
    tokenAddress: "",
    rebalancerAddress: "",
    tokenPriceInUsd: 1,
    tokenPrice24HrChangeInPercentages: 1,
    tokenPrice24HrChangeInUsd: 1,
    apr: 1,
    funds: 1020000,
    avgApr: 1,
    earned: 120,
    decimals: 1,
    deposit: 20000,
    risk: 2,
    borrowRate: 13.3,
    borrowed: 532112
  },
  {
    token: "weth",
    tokenAddress: "",
    rebalancerAddress: "",
    tokenPriceInUsd: 1,
    tokenPrice24HrChangeInPercentages: 1,
    tokenPrice24HrChangeInUsd: 1,
    apr: 1,
    funds: 201010,
    avgApr: 1,
    earned: 1111,
    decimals: 1,
    deposit: 100,
    risk: 3,
    borrowRate: 9.22,
    borrowed: 234320
  },
  {
    token: "wbtc",
    tokenAddress: "",
    rebalancerAddress: "",
    tokenPriceInUsd: 1,
    tokenPrice24HrChangeInPercentages: 1,
    tokenPrice24HrChangeInUsd: 1,
    apr: -1,
    funds: 2.45,
    avgApr: 1,
    earned: 1345,
    decimals: 1,
    deposit: 1200,
    risk: 5,
    borrowRate: 11.2,
    borrowed: 1000000
  }
];
